<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HNG2TFE" failures="1" tests="5" name="LoginTest" time="30.584" errors="0" timestamp="2024-10-15T14:50:21 CEST" skipped="0">
  <testcase classname="LoginTest" name="checkIfLoginWorksCorrectly" time="6.600">
    <failure message="
Multiple Failures (1 failure)
-- failure 1 --
expected: false
 but was: true
at LoginTest.checkIfLoginWorksCorrectly(LoginTest.java:58)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (1 failure)
-- failure 1 --
expected: false
 but was: true
at LoginTest.checkIfLoginWorksCorrectly(LoginTest.java:58)
at LoginTest.checkIfLoginWorksCorrectly(LoginTest.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- checkIfLoginWorksCorrectly -->
  <testcase classname="LoginTest" name="checkIfLoginWithEmptyPasswordAndRandomPhoneNumberIsNotPossible" time="5.487"/>
  <testcase classname="LoginTest" name="checkIfLoginWithEmptyPasswordAndEmptyPhoneNumberIsNotPossible" time="5.563"/>
  <testcase classname="LoginTest" name="checkIfLoginWithEmptyPhoneNumberIsNotPossible" time="5.767"/>
  <testcase classname="LoginTest" name="checkIfLoginWithEmptyPasswordIsNotPossible" time="7.167"/>
</testsuite> <!-- LoginTest -->
