<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-HNG2TFE" failures="1" tests="6" name="FrontEndTests" time="18.202" errors="0" timestamp="2024-10-15T14:50:21 CEST">
  <testcase classname="LoginTest" name="checkIfLoginWithEmptyPasswordAndRandomPhoneNumberIsNotPossible" time="4.561"/>
  <testcase classname="LoginTest" name="checkIfLoginWithEmptyPasswordAndEmptyPhoneNumberIsNotPossible" time="4.561"/>
  <testcase classname="LoginTest" name="checkIfLoginWithEmptyPhoneNumberIsNotPossible" time="4.317"/>
  <testcase classname="LoginTest" name="checkIfLoginWithEmptyPasswordIsNotPossible" time="5.704"/>
  <testcase classname="LoginTest" name="checkIfLoginWorksCorrectly" time="5.59">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (1 failure)
-- failure 1 --
expected: false
 but was: true
at LoginTest.checkIfLoginWorksCorrectly(LoginTest.java:58)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (1 failure)
-- failure 1 --
expected: false
 but was: true
at LoginTest.checkIfLoginWorksCorrectly(LoginTest.java:58)
at LoginTest.checkIfLoginWorksCorrectly(LoginTest.java:61)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- checkIfLoginWorksCorrectly -->
  <testcase classname="DashboardTest" name="getAllFittingBets" time="4.499"/>
</testsuite> <!-- FrontEndTests -->
